module.exports = [
    {
        title: 'kickboxing',
        description: 'kickboxing class for beginners',
        startTime: '7:00 pm',
        endTime: '8:00 pm',
        ageGroup: String,
    },
    {
        title: 'jiu jitsu',
        description: 'jiu jitsu class for beginners',
        startTime: '6:00 pm',
        endTime: '7:00 pm',
        ageGroup: String,
    },
    {
        title: 'karate',
        description: 'kickboxing class for beginners',
        startTime: '7:00 pm',
        endTime: '8:00 pm',
        ageGroup: String,
    },
    {
        title: 'wrestling',
        description: 'kickboxing class for beginners',
        startTime: '7:00 pm',
        endTime: '8:00 pm',
        ageGroup: String,
    },
    {
        title: 'boxing',
        description: 'kickboxing class for beginners',
        startTime: '7:00 pm',
        endTime: '8:00 pm',
        ageGroup: String,
    },
    {
        title: 'child self defense',
        description: 'kickboxing class for beginners',
        startTime: '7:00 pm',
        endTime: '8:00 pm',
        ageGroup: String,
    },
    {
        title: 'advanced jiu jitsu',
        description: 'kickboxing class for beginners',
        startTime: '7:00 pm',
        endTime: '8:00 pm',
        ageGroup: String,
    },
    {
        title: 'advanced boxing',
        description: 'kickboxing class for beginners',
        startTime: '7:00 pm',
        endTime: '8:00 pm',
        ageGroup: String,
    },
    {
        title: 'advanced wrestling',
        description: 'kickboxing class for beginners',
        startTime: '7:00 pm',
        endTime: '8:00 pm',
        ageGroup: String,
    },
]